### ISSUE TITLE
Issue /wp-admin/includes/plugin.php on lin 1419

### ISSUE THREAD

**Issue by ghanton** [ryanve/access#3]
Hi Ryan, I get an error when Access is activated on my site, whats weird is I only get it on mobile and not on desktop.

warning invalid argument supplied for foreach() in wp-admin/includes/plugin.php on lin 1419

It especially happens above or below form areas.

**Comment by ryanve** [comment]
@TravelGo That is weird. Are you sure that Access is the plugin causing the error?
